application/library/forms.py
import re
from datetime import datetime

from flask import request, flash
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, TextAreaField, SubmitField
from wtforms_sqlalchemy.fields import QuerySelectField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired, Regexp

from application import db
from application.models import Style, Org, Person, Video, Publication, Reference, Ref_category, Ref_order

# TRAINING_ADD ---------------------------------------------------------------------------------------------------------

class TrainingAddForm(FlaskForm):
    training_add_source = SelectField(
        'Source', choices=[(c, c.title()) for c in ('video', 'person', 'publication', 'text')], default='Text')

    category = QuerySelectField('Category', query_factory=lambda: Ref_category.query, default='Description')

    video_id = StringField('YouTube ID', default='placeholder', validators=[DataRequired()])
    video_name = StringField('Video name', default='Video name', validators=[DataRequired()])

    style = QuerySelectField('Style', query_factory=lambda: Style.query, allow_blank=True, blank_text='None')

    org = QuerySelectField(
        'Organization', allow_blank=True, blank_text='None',
        query_factory=lambda: Org.query.order_by(Org.acronym))

    # TODO https://gomakethings.com/how-to-create-a-form-input-autocomplete-without-a-library-or-framework/
    person = QuerySelectField(
        'Person', allow_blank=True, blank_text='Person, Unknown',
        query_factory=lambda: Person.query.filter_by(persons_hide=None).order_by(Person.lastName))

    pub = QuerySelectField('Book title', query_factory=lambda: Publication.query.filter_by(format='BOOK').order_by(Publication.title))

    text_field = TextAreaField('Text', widget=TextArea(), validators=[DataRequired()])

    # TODO if video, youtube ID (include pic as example)
    submit = SubmitField('Submit')


# VALIDATION -----------------------------------------------------------------------------------------------------------

def validate_add_reference_form(form, request, route: str, id: int):

#     flash('Request method: ' + request.method, 'info')

    submission = request.form
#         flash(f"""raw submission:
#             {[k + ' - ' + v for k, v in submission.items() if k not in ('csrf_token', 'submit')]}
#             """, 'info')

    src = submission.get('training_add_source')

    video_valid = src != 'video' or (src == 'video' and re.search(r'[-_\w\d]{11}', submission.get('video_id')))
    if form.validate_on_submit() and video_valid:

        # VIDEO ----------------------------------------------------------------------------------------------------
        if submission.get('training_add_source') == 'video':

            video = Video.query.filter_by(URL=submission.get('video_id')).first()
            if not video:
                video = Video()
                db.session.add(video)
                db.session.commit()
                db.session.refresh(video)
#                     flash(f'New video record created with ID {video.id}', 'info')
            else:
#                     flash(f'Previous video record with ID {video.id}', 'info')
                pass

            org_id = submission.get('org')
            video_dict = {
                'style_id': submission.get('style'),
                'org_id': org_id if org_id and org_id != '__None' else None,
                'performer_person_id': submission.get('person').replace('__None', '99999'),
                'name': submission.get('video_name'),
                'URL': submission.get('video_id')
            }

            [setattr(video, k, v) for k, v in video_dict.items()]

#                 flash(f"""video:
#                     {[k + ' - ' + str(v) for k, v in video.__dict__.items() if v and k != '_sa_instance_state']}""",
#                     'info')

            db.session.add(video)
            db.session.commit()

        # BASE ---------------------------------------------------------------------------------------------------------
        glossary_kata = 'glossary' if 'tech' in route else 'kata'

        new_ref_dict = {
            'glossary_id': str(id) if glossary_kata == 'glossary' else None,
            'kata_id': str(id) if glossary_kata == 'kata' else None,
            'category_id': submission.get('category'),
            'person_id': submission.get('person').replace('__None', '99999') if src in ('person', 'video') else None,
            'video_id': video.id if src == 'video' else None,
            'pub_id': submission.get('pub') if src == 'publication' else None,
            'text': submission.get('text_field'),
            'created_date': datetime.now()
        }

        # TODO until can add video/people/pubs on the fly, dropdown menu and separate function for adding people/pub
        new_ref = Reference(**new_ref_dict)
#             flash(f"""new_ref: {[k + ' - ' + str(v) for k, v in new_ref_dict.items() if v]}""", 'info')

        db.session.add(new_ref)
        db.session.commit()
        db.session.refresh(new_ref)  # ID added to new_ref after insert and refresh

        glossary_kata_id = new_ref_dict[f'{glossary_kata}_id']
        ref_len = Ref_order.query.filter_by(**{f'{glossary_kata}_id': glossary_kata_id}).count()
        db.session.add(
            Ref_order(**{f'{glossary_kata}_id': glossary_kata_id, 'ref_id': new_ref.id, 'order': ref_len + 1}))

        db.session.commit()

        flash(f'Your changes have been saved.', 'success')

    else:
        if src == 'video' and not video_valid:
            flash('Check YouTube address for 11-character alphanumeric YouTube ID after "v=".', 'alert')

        for k, v in form.errors.items():
            flash(f"{k} field: {v[0]}", 'danger')

application/library/__init__.py
from flask import Blueprint

bp = Blueprint('library', __name__)

from application.library import routes

application/library/routes.py
import os

from flask import render_template, url_for, redirect, request
from flask_login import current_user, login_required
from flask_babel import _

from application import db
from application.library import bp
from application.models import Org, Person, Dojo, Country, State, Glossary, \
    Reference, Ref_category, Ref_order, Video, Kata, Publication, \
    o, p

from application.library.forms import TrainingAddForm, validate_add_reference_form

@bp.route('/history')
def history():
    pubs = Publication.query.join()
    return render_template("library/history.html", title=_('History'), pubs=pubs)

@bp.route('/orgs')
def orgs():
    return render_template("library/orgs.html", title=_('Organizations'), orgs=Org.query.all())

@bp.route('/org/<int:id>')
def org(id):
    org = Org.query.filter_by(id=id).first_or_404()
    founder = Person.query.filter_by(id=org.founder_person_id).first()
    head_instructor = Person.query.filter_by(id=org.headInstructor_person_id).first()
    president = Person.query.filter_by(id=org.president_person_id).first()
    honbu = Dojo.query.filter_by(id=org.honbu_dojo_id).first()
    honbu_state = State.query.filter_by(id=honbu.state_id).first() if honbu else None
    return render_template(
        "library/org.html", org=org, founder=founder, head_instructor=head_instructor, president=president,
        honbu=honbu, honbu_state=honbu_state,
        google_api_key=os.environ['GOOGLE_API_KEY'], o=o, p=p)

@bp.route('/people')
def people():
    people = Person.query.filter_by(persons_hide=None).order_by(Person.lastName).all()
    return render_template("library/people.html", people=people, enumerate=enumerate, title=_('People'))

@bp.route('/person/<int:id>')
def person(id):
    p = Person.query.filter_by(id=id).first_or_404()
    r = Publication.query.all()
    return render_template("library/person.html", p=p, r=r)

@bp.route('/glossary')
def glossary():
    glossary = Glossary.query.order_by(Glossary.type).all()
    return render_template("library/glossary.html", title=_('Glossary'), glossary=glossary)

@bp.route('/kata_all')
def kata_all():
    pubs = Publication.query.all()
    kata = Kata.query.all()
    return render_template("library/kata_all.html", pubs=pubs, kata=kata, p=p, o=o, enumerate = enumerate, title=_('Kata'))

@bp.route('/kata/<int:id>', methods=['GET', 'POST'])
@login_required
def kata(id):
    k = Kata.query.filter_by(id=id).first_or_404()

    conditions = (Ref_order.kata_id==k.id) & (Ref_order.ref_id==Reference.id)
    refs = k.refs.outerjoin(Ref_order, conditions).add_columns(Ref_order.order).all()

    null_check = [order for ref, order in refs if order]
    if not null_check:
        [db.session.add(Ref_order(kata_id=id, ref_id=r[0].id, order=n + 1)) for n, r in enumerate(refs)]
        db.session.commit()
        refs = k.refs.outerjoin(Ref_order, conditions).add_columns(Ref_order.order).all()

    refs = [ref for ref, order in sorted(refs, key=lambda x: x[1])]
    ref_data = {'ref_type': 'kata', 'ref_type_id': id}

    form = TrainingAddForm()

    if request.method == 'POST':
        validate_add_reference_form(form, request, 'library.kata', id)
        return redirect(url_for('library.kata', id=id))

    return render_template("library/kata.html", title=_('Kata'), k=k, refs=refs, ref_data=ref_data, form=form,
    enumerate=enumerate, len=len)

@bp.route('/kihon')
def kihon():
    return render_template("library/kihon.html", title=_('Kihon'), o=o, p=p)

@bp.route('/kumite')
def kumite():
    return render_template("library/kumite.html", title=_('Kumite'))

@bp.route('/tech/<int:id>', methods=['GET', 'POST'])
@login_required
def tech(id):
    term = Glossary.query.filter_by(id=id).first_or_404()

    conditions = (Ref_order.glossary_id==term.id) & (Ref_order.ref_id==Reference.id)
    refs = term.refs.outerjoin(Ref_order, conditions).add_columns(Ref_order.order).all()

    null_check = [order for ref, order in refs if order]
    if not null_check:
        [db.session.add(Ref_order(glossary_id=id, ref_id=r[0].id, order=n + 1)) for n, r in enumerate(refs)]
        db.session.commit()
        refs = term.refs.outerjoin(Ref_order, conditions).add_columns(Ref_order.order).all()

    refs = [ref for ref, order in sorted(refs, key=lambda x: x[1])]
    ref_data = {'ref_type': 'glossary', 'ref_type_id': id}

    form = TrainingAddForm()

    if request.method == 'POST':
        validate_add_reference_form(form, request, 'library.tech', id)
        return redirect(url_for('library.tech', id=id))

    return render_template("library/tech.html", term=term, refs=refs, ref_data=ref_data, form=form, enumerate=enumerate,
    len=len)

@bp.route('/training')
def training():
    drills = Reference.query \
        .join(Ref_category, Reference.category).filter_by(name='drill') \
        .join(Glossary, Reference.term).order_by(Glossary.word).all()
    return render_template("library/training.html", title=_('Training'), drills=drills)

@bp.route('/media')
def media():
    return render_template("library/media.html", title=_('Media'))

# ----------------------------------------------------------------------------------------------------------------------

def get_ref(ref_type, ref_type_id: int, order: int):
    ref_type_col = getattr(Ref_order, f'{ref_type}_id')
    return Ref_order.query.filter((ref_type_col==ref_type_id) & (Ref_order.order==order)).first_or_404()

@bp.route('/prioritize/<ref_type>/<int:ref_type_id>/<int:order>')
@login_required
def prioritize(ref_type, ref_type_id, order):
    ref_current_id = get_ref(ref_type, ref_type_id, order).id
    ref_above_id = get_ref(ref_type, ref_type_id, order - 1).id

    Ref_order.query.filter_by(id=ref_current_id).update({'order': order - 1})
    Ref_order.query.filter_by(id=ref_above_id).update({'order': order})
    db.session.commit()

    library_url = f"library.{'kata' if ref_type=='kata' else 'tech'}"
    return redirect(url_for(library_url, id=ref_type_id))

@bp.route('/deprioritize/<ref_type>/<int:ref_type_id>/<int:order>')
@login_required
def deprioritize(ref_type, ref_type_id, order):
    ref_current_id = get_ref(ref_type, ref_type_id, order).id
    ref_below_id = get_ref(ref_type, ref_type_id, order + 1).id

    Ref_order.query.filter_by(id=ref_current_id).update({'order': order + 1})
    Ref_order.query.filter_by(id=ref_below_id).update({'order': order})
    db.session.commit()

    library_url = f"library.{'kata' if ref_type=='kata' else 'tech'}"
    return redirect(url_for(library_url, id=ref_type_id))

application/templates/library/history.html
{% extends "base.html" %}

{% block app_content %}

<!-- To edit timeline, update Google Drive Chronology sheet and the rest will update automatically -->
<iframe src='https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1O3fC3TuKyL-P2VG_5UoHEKkR4PifwTyCJUVOnEmFvvk&font=Default&lang=en&initial_zoom=2&height=650'
    width='100%' height='650' webkitallowfullscreen mozallowfullscreen allowfullscreen frameborder='0'></iframe>

<div class='w-50' style='border: 1px solid lightgray'>
    <div class='row'>
        <div class='span6'>
            <h3 style='padding-left:25px'>History</h3></div>
    </div>
    <ul>
        <li><a href='#origin'>Origin</a></li>
        <ul>
            <li><a href='#origin_chinese'>China</a></li>
        </ul>

        <li><a href='#okinawa'>Okinawa</a></li>
        <ul>
            <li><a href="#okinawa_chinese">Chinese instructors</a></li>
            <li><a href="#okinawa_instructors">Okinawan instructors</a></li>
        </ul>

        <li><a href='#japan'>Japan</a></li>
        <ul>
            <li><a href="#japan_styles">Styles</a></li>
            <li><a href="#japan_schools">Schools</a></li>
        </ul>

<!--        <ul>-->
<!--            <li><a href='#Today'>Today</a></li>-->
<!--            <ul>-->
<!--                <li><a href='#Tournaments'>Tournaments</a></li>-->
<!--            </ul>-->
<!--        </ul>-->

    </ul>
</div>
<br>

{% set ns = namespace() %}
{% set ns.pubs = {} %}

{% for i in pubs %}
    {% if i.id == 85 %}
        {{ ns.pubs.update({'redmond': {'p': i}}) | default("", True) }}
    {% elif i.id == 87 %}
        {{ ns.pubs.update({'mccarthy': {'p': i}}) | default("", True) }}
    {% elif i.id == 88 %}
        {{ ns.pubs.update({'cook': {'p': i}}) | default("", True) }}
    {% endif %}
{% endfor %}

<!-- adds alphabetically sorted index to each reference -->
{% for k, v in ns.pubs|dictsort(false) %}
    {{ v.update({'n': loop.index}) | default("", True) }}
{% endfor %}

<h2 id='origin'>Origin</h2>

<p>As Robert Redmond writes, karate originated in Okinawa centuries ago but its
    roots extend to China, Korea, Japan, Taiwan, and other Pacific Rim nations.
    Most of the exchange was from trade and diplomacy, but at times, visitors
    unintentionally washed ashore.
    <sup><a class='citation' data-content="Redmond 17">[{{ ns.pubs['redmond']['n'] }}]</a></sup>
</p>

<h3 id='origin_chinese'>China</h3>

<p>Oral histories and a few documents describe the strong influence of Chinese
    martial arts on Okinawa during the 18th and 19th centuries. Those arts
    historically center around the Shaolin temple in China's Henan province, where
    martial artists from different styles sought refuge when they were being hunted
    by the Qing Dynasty (which lasted from 1644-1912). Chinese boxing developed
    there and spread outwards; these systems, such as
    <a href='#' class='modal_custom_trigger modal_youtube' data-youtube_id='DWo0z_um-Ts'>White Crane</a>,
    <a href='#' class="modal_custom_trigger modal_youtube" data-youtube_id="8Aog6th-hjQ">Five Ancestors</a>,
    <a href='#' class="modal_custom_trigger modal_youtube" data-youtube_id="nRj3WECb8m0">Monk Fist</a>,
    <a href='#' class="modal_custom_trigger modal_youtube" data-youtube_id="Ie1geyJQg2c">Dragon Fist</a>,
    <a href='#' class="modal_custom_trigger modal_youtube" data-youtube_id="Fp9munpIdP0">Lion Boxing</a>,
    <a href='#' class="modal_custom_trigger modal_youtube" data-youtube_id="G90RpGs_ajs">Dog Boxing</a>, and
    <a href='#' class="modal_custom_trigger modal_youtube" data-youtube_id="qCnZRW7IWoE">Tiger Fist</a>,
    were what was then transmitted to the Okinawans.
    <sup><a class="citation" data-content="McCarthy 30, 38">[{{ ns.pubs['mccarthy']['n'] }}]</a></sup>
</p>

<p><small>
    Note: the author is not a kung fu practioner, so the above links representing the various styles
    are assumptions made by the author, and corrections--or links to videos of better quality--are
    welcome.
</small></p>

<h2 id='okinawa'>Okinawa</h2>

<p>Over the centuries, Okinawans and Chinese freely visited and lived in China's
    southeastern Fujian province and Okinawa's Naha and Shuri cities. Especially in
    Fujian's capital Fuzhou, several forms of <i>gongfu</i> (skill through
    perseverance) or <i>quanfa</i> (literally, fist rule, and <i>kenpo</i> in
    Japanese) were taught. As Chinese martial artists freely trained under
    different systems and instructors, those arts evolved over time, while the
    Okinawans preserved the style they had learned within a given period.
    <sup><a class="citation" data-content="Redmond 23-24">[{{ ns.pubs['redmond']['n'] }}]</a></sup>
</p>

<p>The styles of Okinawan <i>toudi</i> (literally, T’ang
    Dynasty hand) that emerged from this interaction came directly from the
    Chinese instructors and their time period, rather than specific Okinawan cities.
    While most famous toudi practitioners came from Naha (a major port city) and
    Shuri (the capital), most karate men by the 19th century were Shuri government
    employees, and the two cities were less than a 20-minute walk apart. Their
    differences more likely represent different points of time of the same Chinese
    martial art, rather than different martial arts altogether. The 1926 designation
    of toudi styles as Naha-Te, Shuri-Te, and Tomari-Te is then an anachronistic
    attempt to systematize those styles.
    <sup><a class="citation" data-content="Redmond 23-24">[{{ ns.pubs['redmond']['n'] }}]</a></sup>
    This
    <a href='#' class="modal_custom_trigger modal_img" data-src='1dDKzoGOZs7kPo1bCZ_kV9bUlLkFC_uvd'
       data-citation="Redmond 26">
        genealogical map
    </a>
    is a good illustration of this, with the individuals further detailed below.
</p>

<h3 id="okinawa_chinese">Chinese instructors</h3>

<p>As Redmond writes, the Okinawans' Chinese martial arts instructors, with the
    exception of <a href="">Chinto</a>, were "government officials with diplomatic
    status [who] interacted with their high-ranking and wealthy counterparts from
    Okinawa." Below are a few influential instructors who contributed to the
    development of Okinawan martial arts. Those mainly known for contributions to
    kata, such as
    Chiang Nan (the <a href="">Heians</a>),
    Kung Hsiang-Chun (<a href=''>Kushanku</a>), and
    Chinto (<a href="">Gankaku</a>)
    are mentioned on their respective kata page.
    <sup><a class="citation" data-content="Redmond 18, 21">[{{ ns.pubs['redmond']['n'] }}]</a></sup><br>
    <small><i>TODO - fix links once pages are up</i></small>
</p>

<h4 id='okinawa_chinese_xinxian'>Wai Xinxian</h4>

<p>Redmond 20: "Not much is known about this man other than his name
    and that he was a friend and associate of Xie Zhongxiang (below). He is thought
    to have taught Monk Fist Boxing in Fuzhou, China to a famous Okinawan instructor
    who moved there for a period,but no one is really sure. He is thought by some to
    be a little older than Xie Zhongxiang."
    <sup><a class="citation" data-content="McCarthy 32">[{{ ns.pubs['mccarthy']['n'] }}]</a></sup>
</p>

<h4 id='okinawa_chinese_zhongxiang'>Xie Zhongxian</h4>

<p>Redmond 21: "Xie Zhongxiang (1852-1930). Known by the
    nickname Ryuru Ko, this man was afriend of Wai Xinxian's and taught Gongfu in
    Fuzhou as well to Okinawans who traveledto meet him. He was the founder of the
    Whooping Crane style of Gongfu and probably studied White Crane and other systems
    - synthesizing them into his own method.
    <sup><a class="citation" data-content="McCarthy 34-39">[{{ ns.pubs['mccarthy']['n'] }}]</a></sup>
</p>

<h4 id='okinawa_chinese_iwah'>Iwah</h4>

<p>
    Redmond 21: "Iwah. A military attaché like Ason [who taught
    the <a href="">Tekkis</a>], Iwah also lived in Fuzhou, China and taught Quanfa
    to Okinawans who traveled there."
    <sup><a class="citation" data-content="Cook 287">[{{ ns.pubs['cook']['n'] }}]</a></sup>
</p>

<h3 id='okinawa_instructors'>Okinawan instructors</h3>

<p>
    As you can see in this
    <a href='#' class="modal_custom_trigger modal_img" data-src='1dDKzoGOZs7kPo1bCZ_kV9bUlLkFC_uvd'
       data-citation="Redmond 26">
        genealogical map
    </a>,
    <a href="{{ url_for('library.person', id=47) }}">Matsumura Sokon</a> received most of the Shorin style kata (blue
    lines), and
    <a href="{{ url_for('library.person', id=48) }}">Arakaki Seisho</a> and
    <a href="{{ url_for('library.person', id=49) }}">Higaonna Kanryo</a>
    received the style (red lines) that that were later called Naha or Goju style. Matsumora Kosaku,
    <a href="{{ url_for('library.person', id=49) }}">Matsumura Sokon</a>,
    <a href="{{ url_for('library.person', id=34) }}">Kenwa Mabuni</a>, and
    <a href="{{ url_for('library.person', id=3) }}">Masatoshi Nakayama</a>
    received both. Though this is a map of the major toudi and karate instructors, of course, there
    are many other contributors that are important but have gone unnamed.
    <sup><a class="citation" data-content="Redmond 26-7">[{{ ns.pubs['redmond']['n'] }}]</a></sup><br>
</p>

<p>
    <small><i>TODO: research shitokai.com/matsumura.html</i></small><br>
    <small><i>TODO: add Itosu and Azato profiles and their influence on Funakoshi</i></small>
</p>

<h4 id='okinawa_instructors_funakoshi'>
    <a href="{{ url_for('library.person', id=1) }}">Gichin Funakoshi</a></h4>

<p>
    Gichin Funakoshi was the first Okinawan to teach karate in Japan
    <sup><a class="citation" data-content="Redmond 33">[{{ ns.pubs['redmond']['n'] }}]</a></sup>.
    He taught toudi for physical education in an
    elementary school in 1901, and in a high school in 1905. In 1902 Shintaro Ogawa, a school commissioner for
    Kagoshima prefecture, witnessed an exhibition of toudi and reported to the Japanese
    Ministry of Education the benefits of toudi. After that, toudi became a part of schools'
    curricula and began to be practiced freely in Japan (JKA India - chief instructors).
    <br>
    <small><i>TODO: add citations; more summary of Funakoshi pre-Japan.</i></small></p>

<h2 id="japan">Japan</h2>

<p>
    During the early 20th century, with Japanese imperialism on the rise and its interest
    in China on the decline, the Japanese term <i>karate</i> gradually replaced the Okinawan term
    <i>toudi</i>. <i>T'ang Dynasty hand</i>, which was implied in the Okinawan term, became
    "void", "sky", or "empty". Thus, 空手 (karate) means <i>empty hand</i>.
    <sup><a class="citation" data-content="Redmond 27">[{{ ns.pubs['redmond']['n'] }}]</a></sup><br>
</p>

<p>
    In this period, technique names were also introduced. Previously, there was no relationship
    between a technique and a single name, as Okinawan masters did not want the application of a
    given movement to be constrained by a single name.
    <sup><a class="citation" data-content="Redmond n">[{{ ns.pubs['redmond']['n'] }}]</a></sup><br>
    <small><i>TODO: add citation</i></small>
</p>

<h3 id="japan_styles">Ryū (Styles)</h3>

<p>
    While Gichin Funakoshi developed Shotokan karate in Japan,
    <a href="{{ url_for('library.person', id=34) }}">Kenwa Mabuni</a>,
    <a href="{{ url_for('library.person', id=35) }}">Chōjun Miyagi</a>, and others
    developed their own styles, such as Shito-ryu, Goju-ryu, Shorin-ryu, and Uechi-ryu.<br>
    <small><i>TODO: add more about other styles, in developing externally to or from Shotokan
    </i></small>
</p>

<h3 id="japan_shotokan">Shotokan</h3>

<h4 id='japan_funakoshi'>
    <a href="{{ url_for('library.person', id=1) }}">Gichin Funakoshi</a></h4>

<p>
    Gichin Funakoshi, for bringing Shotokan karate to Japan and establishing the first karate dojo,
    is its greatest influence.<sup>[0]</sup> He made the Okinawan art more Japanese by incorporating
    elements from the Japanese arts judo and kendo.
    <sup><a class="citation" data-content="Redmond 30">[{{ ns.pubs['redmond']['n'] }}]</a></sup>

    From kendo, he absorbed its competition style, and it may have been Funakoshi's exposure to
    kendo's training method that would lead him to introduce <i>gohon kumite</i> (five-step sparring)--
    <a href='#' class='modal_custom_trigger modal_youtube' data-youtube_id='LYsJKej64TA'>kendo’s uchikomi</a>.
    <sup>[0]</sup>

    Most of his Japanese students were kendo experts, too, like
    <a href="{{ url_for('library.person', id=3) }}">Masatoshi Nakayama</a>,
    who would become the second greatest influence on Shotokan karate.
    <sup><a class="citation" data-content="Redmond 30">[{{ ns.pubs['redmond']['n'] }}]</a></sup><br>
    <small><i>TODO: add [0] citations; add summary of Funakoshi's contributions to bringing karate
        to Japan and developing it; Jigoro Kanno and Funakoshi.</i></small>
</p>

<h2 id="japan_schools">Ryū-ha (Schools)</h2>

<small><i>
    TODO: summary of JKA's development, and JKA vs Keio University and Shotokai Association;
    JKA's split into other organizations; WKF and Olympics
</i></small>
</p>

<h4>References</h4>

{% for k, v in ns.pubs|dictsort(true) %}
    {% set pub, author = v['p'], v['p'].author[0] %}
    <span id={{ k }}>{{ v['n'] }}. {{ author.lastName }}, {{ author.firstName }}</span>.
    <i>
        {%- if pub.store_link %}<a href="{{ pub.store_link }}" target="_blank">{{ pub.title }}</a>
        {%- else %}{{ pub.title }}
        {%- endif %}.
    </i>
    {% if pub.publisher %}
        {{ pub.publisher}}, {{ pub.year.year | default("n.d.", True) }}.
    {% endif %}
    <br>
{% endfor %}

{% endblock %}

application/templates/library/kata.html
{% extends "base.html" %}

{% block app_content %}

<h1>{{ k.name }}
    {% if k.kanji %}({{ k.kanji }}){% endif %}
</h1>

<ul class="list-unstyled">
    {% if k.creator %}
        Creator: <a href="{{ url_for('library.person', id=k.creator.id) }}">
                {{ k.creator.firstName }} {{ k.creator.lastName }}</a><br>
    {% endif %}
</ul>

{% if k.parent_kata %}
    Parent kata:
    {% for n, parent in enumerate(k.parent_kata) %}
         <a href="{{ url_for('library.kata', id=parent.id) }}">{{ parent.name }}</a>
        {%- if n != len(k.parent_kata) - 1 %}, {% endif %}
    {% endfor %}<br>
{% endif %}

{% if k.children_kata %}
    Children kata:
    {% for n, child in enumerate(k.children_kata) %}
        <a href="{{ url_for('library.kata', id=child.id) }}">{{ child.name }}</a>
        {%- if n != len(k.children_kata) - 1 %}, {% endif %}
    {% endfor %}<br>
{% endif %}

{% if k.history %}
    <br>
    <a class="btn btn-secondary" data-toggle="collapse" href="#History" role="button" aria-expanded="false"
       aria-controls="History">History</a><br><br>

    <div id="History" class="collapse">
        {{ k.history | safe }}
        <br><br>
    </div>
{% endif %}

{% set ref_form_header = k.name %}
{% include '_ref.html' %}

<!-- TODO fix kata db entry: sometimes doesn't submit, and id goes under glossary -->

<br><br>

<p><a href="{{ url_for('library.kata_all') }}#Kata List">Back to kata list</a></p>

<!-- TODO add creator altName add kata sidebar -->
<!--// TODO related kata-->

{% endblock %}